// tslint:disable: max-line-length
export const En = {
  error: 'Error',
  success: 'success',
  done: 'Done',
  test: 'Test $arg0',
  OK: 'OK',
  cancel: 'cancel',
  select: 'Select',
  day: 'Day',
  hour: 'Hour',
  minute: 'Minute',
  and: 'and',
  warning: 'Warning',
  textInputPlaceHolder: 'Type Here...',
  // Get Phone Scene --S
  enterTextGetPhoneScene: 'Enter Your Phone Number',
  descriptionGetPhoneScene: 'Enter phone number. ...',
  phoneInputTitleGetPhoneScene: 'Phone Number',
  phoneInputPlaceHolderGetPhoneScene: '09123456789',
  hasCodeGetPhoneScene: 'Have Code?',
  enterButtonGetPhoneScene: 'Enter',
  InvalidPhoneNumberGetPhoneScene: 'invalid phone',
  titleTextGetPhoneSetPassScene: 'Set Password',
  counterTextGetPhoneScene: 'Remaining time for re-request: ',
  // Get Phone Scene --E
  EmailPasswordErrorLoginScene: 'email-password not found',
  ConnectionError: 'connection failed',
  titleConnectionErrorOkDialog: 'connection failed',
  messageConnectionErrorOkDialog: 'connection failed',
  buttonTextConnectionErrorOkDialog: 'ok',
  usernameInputTitleLoginScene: 'Username(Phone Number)',
  enterTextLoginScene: 'Enter',
  passInputTitleLoginScene: 'Password',
  passInputPlaceHolderLoginScene: 'Password...',
  forgotPassLoginScene: 'Forgot Password?',
  EmptyPassLoginScene: 'password is empty',
  loginHeaderLoginScene: 'Login',
  enterButtonLoginScene: 'Login',
  registerRedirectLoginScene: 'No Account? Register',
  loginAttemptOkDialogTitle: 'Login',
  successfulLoginOkDialogMessage: 'You logged in successfully!',
  infoLoginScene: 'Enter username(phone number) & password to login. for new account go to register section',
  editImageTextRegisterScene: 'edit Image',
  firstNameInputTitleRegisterScene: 'First Name',
  lastNameInputTitleRegisterScene: 'Last Name',
  provinceInputTitleRegisterScene: 'State',
  cityInputTitleRegisterScene: 'City',
  addressInputTitleRegisterScene: 'Address',
  firstNameInputPlaceHolderRegisterScene: 'Stephen',
  lastNameInputPlaceHolderRegisterScene: 'Morrison',
  titleRulesOkDialogRegisterScene: 'Rules',
  messageRulesOkDialogRegisterScene: 'Rules Text',
  buttonTextRulesOkDialogRegisterScene: 'Agree',
  EmptyFirstNameRegisterScene: 'FirstName empty',
  EmptyLastNameRegisterScene: 'LastName empty',
  addressRegisterSceneErr: 'Invalid Address',
  EmptyProvinceRegisterScene: 'Province empty',
  EmptyCityRegisterScene: 'city empty',
  titleEmptyImageOkDialogRegisterScene: 'image empty',
  messageEmptyImageOkDialogRegisterScene: 'image empty',
  buttonTextEmptyImageOkDialogRegisterScene: 'ok',
  titleProvinceSelectDialogRegisterScene: 'select province',
  descriptionProvinceSelectDialogRegisterScene: 'select your province',
  titleCitySelectDialogRegisterScene: 'select city',
  descriptionCitySelectDialogRegisterScene: 'select your city',
  enterButtonRegisterScene: 'Enter',
  descriptionSetPassScene: 'Set your Password',
  passInputTitleSetPassScene: 'Password',
  passInputPlaceHolderSetPassScene: 'Password...',
  passConfirmInputTitleSetPassScene: 'Confirm password',
  passConfirmInputPlaceHolderSetPassScene: 'Confirm password...',
  InvalidPasswordSetPassScene: 'invalid password',
  InvalidPasswordConfirmSetPassScene: ' invalid password Confirm',
  titleInvalidImageOkDialogRegisterScene: 'invalid image title',
  messageInvalidImageOkDialogRegisterScene: 'invalid image message',
  buttonTextInvalidImageOkDialogRegisterScene: 'ok',
  enterButtonSetPassScene: 'Enter',
  // VerifyOtpScene --S
  enterTextVerifyOtpScene: 'Enter',
  descriptionVerifyOtpScene: 'Enter sended code',
  codeInputTitleVerifyOtpScene: 'Verify Code',
  codeInputPlaceHolderVerifyOtpScene: 'Write the code...',
  missedVerifyOtpScene: 'sms missed?',
  sendAgainVerifyOtpScene: 'send again',
  enterButtonVerifyOtpScene: 'Enter',
  remainingTriesVerifyOTPScene: 'Remaining Tries',
  descriptionVerifyOTPScene: 'Enter the code.\n$arg0',
  editPhoneNumberVerifyOTPScene: 'Edit Phone Number',
  // VerifyOtpScene --E
  textSplashScene: 'Fruit Sales System',
  upTextSlide1IntroductionScene: 'Fruit and Greengrocery',
  downTextSlide1IntroductionScene: 'In Best Price',
  upTextSlide2IntroductionScene: 'Fruit and Greengrocery',
  downTextSlide2IntroductionScene: 'Fast',
  upTextSlide3IntroductionScene: 'Fruit and Greengrocery',
  downTextSlide3IntroductionScene: 'Direct',
  nextButtonIntroductionScene: 'Next',

  // ProductsSceneTexts
  exitAppMessageProductsScene: 'To exit app press back button again',
  auction: 'Sale (Auction)',
  productRequest: 'Product request',
  quickSale: 'Quick sale',
  searchTextProductsScene: 'search...',
  searchTextToolbarProductsScene: 'Search',
  messageBarProductsScene: 'Pull down to refresh',

  // SearchSceneTexts
  searchTextToolbarSearchScene: 'Search for Product',
  doneTextToolbarSearchScene: 'Search',
  selectAllDialogSearchScene: 'Select All',
  titleProductTypeSelectDialogSearchScene: 'Select Product Types',
  descriptionProductTypeSelectDialogSearchScene: 'Please select fruits you want to search for',
  placeHolderSearchEditTextSearchScene: 'search ...',
  titleProvinceSelectDialogSearchScene: 'Select Province',
  descriptionProvinceSelectDialogSearchScene: 'select your province',
  titleCitySelectDialogSearchScene: 'Select City',
  descriptionCitySelectDialogSearchScene: 'select your city',
  productTypeHeaderTextSearchScene: 'Product Type',
  weightLimitHeaderTextSearchScene: 'Weight Limit',
  searchButtonTextSearchScene: 'search',

  // SearchResultSceneTexts
  searchTextSearchResultScene: 'Search',
  searchTextToolbarSearchResultScene: 'Search Results',
  noResultFoundTitleokDilogSearchResultScene: 'No Result',
  noResultFoundMessageokDilogSearchResultScene: 'No result founded',

  // Auction Sale --S
  toolbarTitleAuctionSaleScenes: 'Auction Sales',
  nextButtonAuctionScenes: 'Next',
  backButtonAuctionScenes: 'Previous',
  confirmAuctionSale: 'Confirm',
  termsStepOneLabel: 'Condition & Terms',
  termsStepTwoLabel: 'Product Info',
  termsStepThreeLabel: 'Store House',
  termsStepFourLabel: 'Sale Info',
  termsStepFiveLabel: 'Picture Upload',
  // Auction Participate --S
  sellerCreditAuctionParticipate: 'seller credit',
  buyerCreditAuctionParticipate: 'buyer credit',
  timeLeftAuctionParticipate: 'remaining time',
  headerTextAuctionParticipateImmediate: 'Immediate',
  headerTextAuctionParticipateAuction: 'Auction',
  headerTextAuctionParticipateTender: 'Tender',
  currentUnitPriceAuctionParticipateImmediate: 'unit price',
  currentUnitPriceAuctionParticipateAuction: 'current unit price',
  currentUnitPriceAuctionParticipateTender: 'maximum unit price',
  currentPriceAuctionParticipateImmediate: 'total price',
  currentPriceAuctionParticipateAuction: 'current total price',
  deliveryTimeAuctionParticipate: 'delivery time',
  priceLimitAuctionParticipate: 'maximum unit price',
  priceLimitTenderParticipate: 'minimum unit price',
  productDescriptionAuctionParticipate: 'product description',
  participateAuctionParticipateImmediate: 'I\'m the buyer',
  participateAuctionParticipateAuction: 'participate in the auction',
  participateAuctionParticipateTender: 'participate in the tender',
  myParticipationAuctionParticipate: 'my participation',
  myParticipationOkDialogButtonAuctionParticipate: 'ok',
  participateRulesYesNoDialogTitleQuickSaleParticipation: 'Quick sale rules',
  participateRulesYesNoDialogTitleTenderParticipation: 'Tender rules',
  participateRulesYesNoDialogTitleAuctionParticipation: 'Participation Rules',
  participateRulesYesNoDialogMessageQuickSaleParticipation: 'rules to participate quick sale',
  participateRulesYesNoDialogMessageTenderParticipation: 'rules to participate tender',
  participateRulesYesNoDialogMessageAuctionParticipation: 'Rules',
  participateRulesYesNoDialogYesButtonAuctionParticipate: 'Accept',
  participateRulesYesNoDialogNoButtonAuctionParticipate: 'Deny',
  participateYesNoDialogTitleAuctionParticipate: 'Participate',
  participateYesNoDialogTitleQuickSaleParticipate: 'Participate',
  participateYesNoDialogTitleTenderParticipate: 'Participate',
  participateYesNoDialogMessageFirstBidParticipate: 'You are about to add first bid for this product with base price of $arg0',
  participateYesNoDialogMessageParticipate: 'with this request unit price will be changed from $arg0 to $arg1',
  participateQuickSaleYesNoDialogMessageParticipate: 'You are about to buy this product',
  participateQuickSaleYesNoDialogYesButtonAuctionParticipate: 'Buy',
  participateYesNoDialogYesButtonAuctionParticipate: 'Participate',
  participateYesNoDialogNoButtonAuctionParticipate: 'Decline',
  successBidParticipate: 'Your request submitted successfully',
  successQuickSaleBidParticipate: 'Buy completed',
  cargoWeightAddProductScene: 'Cargo Weight:',
  totalCargoPriceAddProductSale: 'Total price of cargo',
  cargoLocationAddProductSale: 'Location:',
  saleTypeAddProductSale: 'Sale Type:',
  auctionSaleType: 'Auction',
  confirmDataDialogTitleAddProductScene: 'Confirm Information',
  confirmButtonTextAddProductScene: 'Pay & Confirm Sale',
  increaseCreditDataDialogCreateAuctionSale: 'Increase Credit',
  // Accept Rules Scene --S
  termsTitleAcceptTermsScene: 'Conditions & Terms\n For Auction Sales',
  termsAndConditionsAcceptTermsScene: // TODO: REAL english Text must be replaced
    `All Rules is based on Republic Islamic Of Iran Laws. User must follow the rules.

- Minimum Weight For Product Is 10Kg
- Product Grade is divided to three types
- StoreHouse is necessary for Product
  `,
  tenderTermsTitleAcceptTermsScene: 'rules for adding tender',
  tenderTermsAndConditionsAcceptTermsScene: 'tender rules',
  termsCheckBoxTextAcceptTermsScene: 'I accept conditions & terms',
  // Accept Rules Scene --E

  // Enter Product Info Scene --S
  titleProductInfoScene: 'Product Information',
  categoryProductInfoScene: 'Product Category',
  productTypeProductInfoScene: 'Product Name',
  subProductTypeProductInfoScene: 'Type',
  productGradeProductInfoScene: 'Grade',
  productWeightProductInfoScene: 'Cargo Weight (Kg)',
  productTypeSelectorError1ProductInfoScene: 'Select a category first',
  subTypeSelectorError1ProductInfoScene: 'Select a name first',
  // Enter Product Info Scene --E

  // StoreHouse Scene --S
  modifyButtonStoreHouseCard: 'Modify',
  storeWordStoreHouseCard: 'Store',
  productWeightUnitProductCard: 'Kg',
  imageLabelProductCard: 'Sale(Auction)',
  chooseStoreHouseTitleStoreHouseScene: 'Choose Storehouse ',
  addStoreHouseButtonStoreHouseScene: 'Add Storehouse',
  deleteStoreHouseWarningStoreHouseScene: 'Are you sure about deleting this storehouse?',
  // StoreHouse Scene --E

  // AddStoreHouse Scene --S
  addStoreHouseTitleAddStoreHouseScene: 'Add Storehouse',
  editStoreHouseTitleAddStoreHouseScene: 'Edit Storehouse',
  locationVerifyButtonTextAddStoreHouseScene: 'Verify Location',
  locationAddStoreHouse: 'Location Name...',
  nameAddStoreHouseScene: 'Name',
  provinceAddStoreHouseScene: 'Province',
  provinceSelectorTitleAddStoreHouseScene: 'Provinces',
  cityAddStoreHouseScene: 'city',
  citySelectorTitleAddStoreHouseScene: 'Cities',
  addressAddStoreHouseScene: 'Address',
  confirmButtonAddStoreHouseScene: 'Confirm',
  provinceNotSelectedcitySelectorErrorAddStoreHouseScene: 'Select a Province first',
  provinceSelectorErrorAddStoreHouseScene: 'Province needed',
  citySelectorErrorAddStoreHouseScene: 'City needed',
  nameEditTextErrorAddStoreHouseScene: 'Name needed',
  addressEditTextErrorAddStoreHouseScene: 'Address needed',
  // AddStoreHouse Scene --E

  // SaleInfoScene --S
  titleSaleInfoScene: 'Sale Information',
  priceSelectorLabelSaleInfoScene: '1Kg Price',
  auctionDurationSelectorLabelSaleInfoScene: 'Auction Duration (Day)',
  quickSaleDurationSelectorLabelSaleInfoScene: 'Sale Duration (Day)',
  cargoDeliverySelectorLabelSaleInfoScene: 'Cargo Delivery Date',
  saleDescriptionSaleInfoScene: 'Selling Product and Cargo Description',
  // SaleInfoScene --E

  // Confirm Product Scene --S
  pricePerUnitAddProductScenes: 'Price of 1Kg:',
  addProductStartTimeConfirmScene: 'Starting Date:',
  cargoDeliveryDateConfirmScene: 'Cargo Delivery Date:',
  productAndCargoDescriptionConfirm: 'Product & Cargo Description',
  uploadPictureAndVideoConfirmScene: 'Picture & Video Uploading',
  guideButtonConfirmScene: 'Picture & Video Upload Guide',
  uploadPictureButtonConfirmScene: 'Upload Product Picture',
  uploadVideoButtonConfirmScene: 'Upload StoreHouse Video',
  successAddProductConfirmAuctionScene: 'Product added successfully',
  noImageChosenErrorConfirmScene: 'Cant add product without image',
  // Confirm Product Scene --E
  // Auction Sale --E

  // Quick Sale --S
  toolbarTitleQuickSaleSaleScenes: 'Quick Sale',
  nextButtonQuickSaleScenes: 'Next',
  backButtonQuickSaleScenes: 'Previous',
  confirmQuickSaleSale: 'Confirm',
  termsStepOneLabelQuickSaleScenes: 'Condition & Terms',
  termsStepTwoLabelQuickSaleScenes: 'Product Info',
  termsStepThreeLabelQuickSaleScenes: 'Store House',
  termsStepFourLabelQuickSaleScenes: 'Sale Info',
  termsStepFiveLabelQuickSaleScenes: 'Picture Upload',
  pricePerUnitQuickSaleScenes: 'Price per unit',
  cargoWeightQuickSaleScenes: 'Cargo Weight:',
  totalCargoPriceQuickSaleScenes: 'Total price of cargo',
  cargoLocationQuickSaleScenes: 'Location:',
  saleTypeQuickSaleScenes: 'Sale Type:',
  quickSaleSaleTypeQuickSaleScenes: 'Quick Sale',
  confirmDataDialogTitleCreateQuickSaleScene: 'Confirm Information',
  confirmButtonTextCreateQuickSaleScene: 'Pay & Confirm Sale',
  increaseCreditDataDialogCreateQuickSaleSale: 'Increase Credit',
  // Quick Sale Accept Rules Scene --S
  termsTitleQuickSaleAcceptTermsScene: 'Conditions & Terms\n For Auction Sales',
  termsAndConditionQuickSaleAcceptTermsScene:
    `Rules`
  ,
  termsCheckBoxTextQuickSaleAcceptTermsScene: 'I accept conditions & terms',
  // Quick Sale  Accept Rules Scene --E
  // Quick Sale Auction Sale --E

  // Tender --S
  tender: 'Tender',
  tenderThirdStepCreateTenderScene: 'Location',
  tenderFourthtepCreateTenderScene: 'Specification',
  tenderToolbarTitleCreateTenderScene: 'Tender',
  tenderDurationCreateTenderScene: 'Tender Duration (Day)',
  tenderDescriptionTitle: 'Description of product',
  tenderSaleInfoSceneTitle: 'Product Specification',
  // Tender --E
  // EditProduct --S
  editPageTitleEditProductScene: 'Edit',
  auctionPageTitleEditProductScene: 'Auction Sale',
  quickSalePageTitleEditProductScene: 'Quick Sale',
  tenderPageTitleEditProductScene: 'Bid purchase',
  baseCostTitleEditProductScene: 'Base Price Kilo (Only reducible)',
  weightTitleEditProductScene: 'Load Weight',
  auctionDurationTitleEditProductScene: 'Auction Duration',
  productArraivalTimeTitleEditProductScene: 'Delivery date',
  productInformationTitleEditProductScene: 'Description of load and product for sale',
  uploadPicAndMovieTitleEditProductScene: 'Upload picture',
  uploadPicButtonEditProductScene: 'Upload picture of product',
  uploadMovieButtonEditProductScene: 'Upload film of Storehouse',
  uploadhelperTextEditProductScene: 'Photos quality guide',
  confirmButtonEditProductScene: 'Confirm',
  tenderDurationTitleEditProductScene: 'Tender Duration',
  productRequestInformationTitleEditProductScene: 'Description of load and product requested',
  fixErrorsTextEditProductScene: 'Please fix wrong items',
  emptycostErrorTextEditProductScene: 'Please insert cost',
  increseCostErrorEditProductScene: 'Only reducible',
  emptyInformationErrorEditProductScene: 'Please insert information',
  // EditProduct --E

  // Password Dialog --S
  titlePasswordDialog: 'Authorization',
  messagePasswordDialog: 'Enter your password',
  buttonPasswordDialog: 'continue',
  wrongPasswordMessagePasswordDialog: 'Password is incorrect',
  // Password Dialog --E

  // HomeSceneText
  personalTabTextHomeScene: 'Personal',
  homeTabTextHomeScene: 'Home',

  // AddProductDialog
  titleAddProductDialog: 'New Product',
  addAuctionAddProductDialog: 'Auction Sale',
  addQuickSaleAddProductDialog: 'Quick Sale',
  addTenderAddProductDialog: 'Tender Offer',

  // Date --S
  // Month --S
  month1: 'January',
  month2: 'February',
  month3: 'March',
  month4: 'April',
  month5: 'May',
  month6: 'June',
  month7: 'July',
  month8: 'August',
  month9: 'September',
  month10: 'October',
  month11: 'November',
  month12: 'December',
  // Month --E
  // Date --E

  // ProfileScene
  notifCardTitleProfileScene: 'Notifications',
  myProductsButtonProfileScene: 'My Products',
  myParticipationProfileScene: 'My Participation',
  currentUnitPriceAuctionProfileScene: 'current unit price',

  // ProfileProductCard
  productStateProfileProductCard: 'State',
  messageProfileProductCard: 'Message',
  activeProductProfileProductCard: 'Active',
  passiveProfileProductCard: 'Done',
  remainingTimeProfileProductCard: 'The remaining time is $arg0',
  endProfileProductCard: 'It has been finished',

  // NotificationsScene
  toolbarTitleNotificationsScene: 'Notifications',
  seenMessageNotificationsScene: 'seen',
  notSeenMessageNotificationsScene: 'unseen',

  // EditProfileScene
  toolbarTitleEditProfileScene: 'Personal Info',
  editInformationButtonEditProfileScene: 'Edit Info',
  logoutButtonEditProfileScene: 'Logout',
  changePasswordButtonEditProfileScene: 'Change Password',
  addCreditButtonEditProfileScene: 'Add Credit',
  storehouseTabEditProfileScene: 'Storehouses',
  addStoreHouseButtonEditProfileScene: 'Add Storehouse',
  tenderLocationTitleStoreHouseScene: 'Delivery Location',

  // ProfileInfoCard
  virtualCreditProfileInfoCard: 'Virtual Credit',
  financialCreditProfileInfoCard: 'Financial Credit',
  financialEquivalentProfileInfoCard: 'financial equivalence',

  // EditPersonalInfoScene
  toolbarTitleEditPersonalInfoScene: 'Edit Personal Info',
  fNameEditTextTitleEditPersonalInfoScene: 'First Name',
  lNameEditTextTitleEditPersonalInfoScene: 'Last Name',
  ProvinceEditTextTitleEditPersonalInfoScene: 'Province',
  CityEditTextTitleEditPersonalInfoScene: 'City',
  saveChangesButtonEditPersonalInfoScene: 'Save Changes',

  // EditPasswordScene
  rulesEditPasswordScene: 'Enter Your New Password',
  toolbarTitleEditPasswordScene: 'Change Password',
  currentPasswordEditPasswordScene: 'Current Password',
  newPasswordEditPasswordScene: 'New Password',
  repeatCurrentPasswordEditPasswordScene: 'ReEnter New Password',
  confirmEditPasswordScene: 'Confirm',
  requiredEditTextErrorEditPasswordScene: 'Required',
  currentPasswordMismatchEditTextErrorEditPasswordScene: 'Wrong Password',
  newPasswordMismatchEditTextErrorEditPasswordScene: 'New Password Mismatch',
  newPasswordNotSuitableEditTextErrorEditPasswordScene: 'Not Suitable Password',
  verificationCodeEditTextEditPasswordScene: 'Verification Code',
  successfulOperationEditPasswordScene: 'Operation successful',
  failedOperationEditPasswordScene: 'Operation failed',
  successVerificationRequestEditPasswordScene: 'Verification will be send for you',

  // EditPasswordOTPScene
  messageEditPasswordOTPScene: 'Enter received verification code inorder to change password',
  verificationCodeEditPasswordOTPScene: 'Verification Code',
  resendSMSEditPasswordOTPScene: 'Resend sms',
  // Scroll Selector --S
  deliveryDateTitleScrollDialog: 'Delivery Date',
  auctionLengthTitleScrollDialog: 'Auction Length',
  quickSaleLengthTitleScrollDialog: 'Sale length',
  tenderLengthTitleScrollDialog: 'Tender Length',
  weightTitleScrollDialog: 'Cargo Weight',

  // Scroll Selector --E

  // Increase Credit --S
  titleIncreaseCreditsScene: 'Increase Financial Credit',
  topTextIncreaseCreditsScene: 'Enter the amount of credit enhancement you want in Toman then select the redirect button to the bank.',
  labeTitleEditTextIncreaseCreditsScene: 'Credit Increase Amount (Toman)',
  buttonTextIncreaseCreditsScene: 'Navigate to the banking portal',
  // Increase Credit --E

  // Result Increase Credit --S
  costTextResultIncreaseCreditsScene: 'Amount of',
  addedTextResultIncreaseCreditsScene: 'added to your financial credit.',
  buttonTextResultIncreaseCreditsScene: 'Confirm',
  // Result Increase Credit --E

  // Owner Manage Auction Sale Scene --S
  toolbarTitleOwnerManageAuctionSaleScene: 'Auction sale',
  stepperStep1TitleOwnerManageAuctionSaleScene: 'still in sale',
  stepperStep2TitleOwnerManageAuctionSaleScene: 'Send cargo',
  stepperStep3TitleOwnerManageAuctionSaleScene: 'payment & review',
  buyerInfoManageAuctionSaleScene: 'Buyer info',
  cancelAuctionManageAuctionSaleScene: 'Cancel',
  cancelMessageAuctionManageAuctionSaleScene: 'If you are sure of your cancellation, please press the OK button',
  editProductOwnerManageAuctionScene: 'Edit product',
  offerOwnerManageAuctionScene: 'Offers',
  noOfferOwnerManageAuctionScene: 'no offer',
  remainTimeOwnerManageAuctionScene: 'until auction ends',
  endTimeWaitStatusTextOwnerManageAuctionScene: 'Time ends - wait for buyer response',
  priceLimitWaitStatusTextOwnerManageAuctionScene: 'Price ceiling - wait for buyer response',
  sendingCargoWaitMessageOwnerManageAuctionScene: 'Once the buyer is ready, contact us and the interface times are posted',
  endTimeStatusTextOwnerManageAuctionScene: 'Time ends - call Buyer',
  priceLimitStatusTextOwnerManageAuctionScene: 'Price ceiling - call buyer',
  sendingCargoMessageOwnerManageAuctionScene: 'After sending the cargo, press the button below',
  inQueueOwnerManageAuctionScene: 'person(s) in queue',
  sendingCargoButtonTextOwnerManageAuctionScene: 'I sent the cargo',
  waitForCargoArrivalStatusTextOwnerManageAuctionScene: 'Waiting for cargo arrival',
  waitForCargoArrivalMessageTextOwnerManageAuctionScene: 'After Buyer confirmation \nThe charge will be added to the financial score',
  cargoArrivedStatusTextOwnerManageAuctionScene: 'Cargo arrived at destination',
  cargoArrivedMessageTextOwnerManageAuctionScene: 'After Buyer confirmation \nThe charge will be added to the financial score',
  endDealStatusTextOwnerManageAuctionScene: 'Charge added to your financial credit',
  endDealMessageTextOwnerManageAuctionScene: 'Press the button below to end the transaction',
  endDealButtonTextOwnerManageAuctionScene: 'End of the transaction',
  // Owner Manage Auction Sale Scene --E

  // Participate Manage Auction Sale Scene --S
  toolbarTitleParticipateManageAuctionSaleScene: 'Participate in auction',
  quietAuctionManageAuctionSaleScene: 'Quiet',
  quietMessageAuctionManageAuctionSaleScene: 'Press OK if you are sure of your bid withdrawal',
  sellerInfoManageAuctionSaleScene: 'Seller info',
  stepperStep1TitleParticipateManageAuctionSaleScene: 'Bidding',
  stepperStep2TitleParticipateManageAuctionSaleScene: 'Pay the cost',
  stepperStep3TitleParticipateManageAuctionSaleScene: 'Shipping by Seller',
  stepperStep4TitleParticipateManageAuctionSaleScene: 'Cargo Confirmation and Poll',
  offerHigherPriceButtonParticipateManageAuctionSaleScene: 'Highest bid',
  offerHigherPriceMessageButtonParticipateManageAuctionSaleScene: 'The price per kilo will increase from $ arg0 to $ arg0 and you will win the same price if there is no other bid or end of auction.',
  yourPriceParticipateManageAuctionSaleScene: 'your price',
  tempWinnerParticipateManageAuctionSaleScene: 'Current winner',
  winnerParticipateManageAuctionSaleScene: 'Winner',
  endTimeParticipateManageAuctionSaleScene: 'Check Out Time - price',
  priceLimitParticipateManageAuctionSaleScene: 'Price ceiling - price',
  inQueueParticipateManageAuctionSaleScene: 'You are in the queue',
  payCostParticipateStatusTextManageAuctionSaleScene: 'Awaiting Payment',
  payCostParticipateButtonTextManageAuctionSaleScene: 'Paying with financial credit',
  payCostParticipateMessageTextManageAuctionSaleScene: 'Amount of money That had to be paid',
  waitForSendCargoStatusTextParticipateManageAuctionSaleScene: 'Waiting for sending cargo by seller',
  waitForSendCargoMessageTextParticipateManageAuctionSaleScene: 'Contact seller to send cargo',
  cargoSentParticipateStatusTextManageAuctionSaleScene: 'Cargo sent by seller',
  cargoSentParticipateMessageTextManageAuctionSaleScene: 'Press the button below after receiving the cargo',
  getCargoParticipateManageAuctionSaleScene: 'The cargo was delivered',
  confirmCargoStatusTextParticipateManageAuctionSaleScene: 'Delivery times received',
  confirmCargoMessageTextParticipateManageAuctionSaleScene: 'Press the button below if the cargo is confirmed',
  confirmCargoButtonParticipateManageAuctionSaleScene: 'I confirm the cargo',
  // Participate Manage Auction Sale Scene --E

  // Owner Manage Quick sale Sale Scene --S
  toolbarTitleOwnerManageQuickSaleSaleScene: 'Quick sale',
  stepperStep1TitleOwnerManageQuickSaleScene: 'Waiting for the buyer',
  stepperStep2TitleOwnerManageQuickSaleScene: 'Send Cargo',
  stepperStep3TitleOwnerManageQuickSaleScene: 'Get Charge and Survey',
  noBuyerOwnerManageQuickSaleScene: 'No Buyer',
  editAdOwnerManageQuickSaleScene: 'Edit Ad',
  contactBuyerOwnerManageQuickSaleScene: 'Call the buyer',
  cancelQuickSaleManageQuickSaleSaleScene: 'Cancel Sell',
  cancelMessageQuickSaleManageQuickSaleSaleScene: 'If you are sure of cancellation, press the OK button',
  waitStatusTextOwnerManageAuctionScene: 'Awaiting Times Buyer Preparation Announcement',
  waitMessageOwnerManageAuctionScene: 'After the buyer is ready, call and ship',
  // Owner Manage Quick sale Sale Scene --S

  // Owner Manage Tender Sale Scene --S
  toolbarTitleOwnerManageTenderSaleScene: 'Tender buy',
  stepperStep1TitleOwnerManageTenderSaleScene: 'Bidding',
  stepperStep2TitleOwnerManageTenderSaleScene: 'Pay the cost',
  stepperStep3TitleOwnerManageTenderSaleScene: 'Shipping by Seller',
  stepperStep4TitleOwnerManageTenderSaleScene: 'Load Confirmation and Poll',
  remainTimeOwnerManageTenderScene: 'Till the end',
  sellerInfoManageTenderSaleScene: 'Sender Contact',
  cancelTenderManageTenderSaleScene: 'Cancel Tender',
  cancelMessageTenderManageTenderSaleScene: 'If you are sure of your cancellation, press the OK button',
  // Owner Manage Tender Sale Scene --E

  // Participate Manage Tender Sale Scene --S
  toolbarTitleParticipateManageTenderSaleScene: 'Tender participate',
  stepperStep1TitleParticipateManageTenderSaleScene: 'Bidding',
  stepperStep2TitleParticipateManageTenderSaleScene: 'Send Cargo',
  stepperStep3TitleParticipateManageTenderSaleScene: 'Get Charge and Survey',
  remainTimeParticipateManageTenderScene: 'Till the end',
  sellerInfoParticipateManageTenderSaleScene: 'Buyer Contact Information',
  quietParticipateManageTenderSaleScene: 'Tender withdrawal',
  quietMessageParticipateManageTenderSaleScene: 'If you are sure of cancellation, press the OK button',
  endTimeWaitStatusTextParticipateManageTenderScene: 'Time Out - wait for buyer response',
  priceLimitWaitStatusTextParticipateManageTenderScene: 'Price ceiling - wait for buyer response',
  endTimeStatusTextOwnerManageTenderScene: 'Time Out - Contact the Buyer',
  priceLimitStatusTextOwnerManageTenderScene: 'Price floor - contact the Buyer',
  // Participate Manage Tender Sale Scene --E

  // Participate Manage Quick Sale Scene --S
  toolbarTitleParticipateManageQuickSaleScene: 'Quick Sales Company',
  stepperStep1TitleParticipateManageQuickSaleScene: 'Buying Announcement',
  stepperStep2TitleParticipateManageQuickSaleScene: 'Pay the cost',
  stepperStep3TitleParticipateManageQuickSaleScene: 'Shipping by Seller',
  stepperStep4TitleParticipateManageQuickSaleScene: 'Cargo Confirmation and Poll',
  quietParticipateManageQuickSaleScene: 'Cancel Shopping',
  quietMessageParticipateManageQuickSaleScene: 'If you are sure of your withdrawal from the purchase, press the OK button',
  inQueueParticipateManageQuickSaleScene: 'Waiting in line',
  youInQueueParticipateManageQuickSaleScene: 'You are $arg0 person in waiting queue',
  // Participate Manage Tender Sale Scene --E

  // Base Manage Scene --S
  confirmCargoDialogTitleBaseManageScene: 'Confirm Received Cargo',
  confirmCargoDialogMessageBaseManageScene: 'If you confirm the weight and quality of the received cargo, press the button below.',
  confirmCargoDialogButtonBaseManageScene: 'I confirm',
  deliverCargoDialogTitleBaseManageScene: 'Delivery Confirmation',
  deliverCargoDialogMessageBaseManageScene: 'Press the button below if you received the cargo.',
  deliverCargoDialogButtonBaseManageScene: 'I got delivered',
  payCostMessageDialogBaseManageScene: `Pay for:
     $arg0 k $arg1 $arg2
     $arg3 Toman
     Total charge cost:
     $ arg4 Toman`,
  payCostIncreaseDialogBaseManageScene: 'Increase credit',
  payCostTitleDialogBaseManageScene: 'Pay the cost',
  payCostIncreaseButtonTextDialogBaseManageScene: 'Payment from financial credit',
  sellerTitleDialogBaseManageScene: 'Seller Contact Information',
  buyerTitleDialogBaseManageScene: 'Buyer Contact Information',
  sellerNameBaseManageScene: 'Seller Name:',
  buyerNameBaseManageScene: 'Buyer name',
  phoneNumberBaseManageScene: 'Phone number:',
  storehouseAddressBaseManageScene: 'Warehouse Address:',
  viewStorehouseBaseManageScene: 'View Warehouse on Map',
  callBaseManageScene: 'Contact',
  try5MinLaterStatusTextManageScenes: 'The system is processing your request',
  try5MinLaterMessageTextManageScenes: 'Please try again in a few minutes',
  successfulStatusTextManageScenes: 'Successful Deals',
  successfulMessageTextManageScenes: 'Click here to view receipt',
  unsuccessfulStatusTextManageScenes: 'Unsuccessful deal',
  unsuccessfulMessageTextManageScenes: 'Click here to view receipt',
  successfulTitleTextManageScenes: 'Receipt - successful deal',
  unsuccessfulTitleTextManageScenes: 'Receipt - unsuccessful deal',
  // Base Manage Scene --E

  // Receipt card --S
  scoreTextReceiptScene: '$arg0 points to you:',
  receivedMoneyTextReceiptScene: 'Amount received with 4% deduction:',
  auctionTextReceiptScene: 'Auction:',
  tenderTextReceiptScene: 'Tender offer:',
  quickReceiptScene: 'Sale:',
  startTextReceiptScene: 'Beginning',
  endTextReceiptScene: 'the end',
  endReasonTextReceiptScene: 'Cause of end:',
  participantsNumberTextReceiptScene: ':participants',
  basePriceTextReceiptScene: 'base price:',
  finalPriceTextReceiptScene: 'The final price:',
  cargoSendDateTextReceiptScene: 'Shipping Date:',
  cargoDeliveryDateTextReceiptScene: 'Date of delivery:',
  statusTextReceiptScene: 'Status:',
  noBidFailedStatusReceiptScene: 'Automatic cancellation of ads without participants',
  quietStatusReceiptScene: 'Cancellation of price offer',
  // Receipt card --E

  // Home Scene Tab Bar --S
  addProductButtonHomeSceneTabBar: 'ثبت آگهی',
  // Home Scene Tab Bar --E

  // Survey Scene --S
  buyer: 'Buyer',
  seller: 'Seller',
  mivanet: 'Mivanet',
  titleSurveyScene: 'Survey from',
  advantageTabSurveyScene: 'Advantages',
  disadvantageTabSurveyScene: 'Disadvantages',
  extraInformationSurveyScene: 'Extra information',
  submitButtonSurveyScene: 'Submit comment',
  badRatingText: 'Bad',
  poorRatingText: 'Poor',
  acceptableRatingText: 'Acceptable',
  goodRatingText: 'Good',
  excellentRatingText: 'Excellent',

  advantagesBuyerRule1: '',
  advantagesBuyerRule2: '',
  advantagesBuyerRule3: '',
  advantagesBuyerRule4: '',
  advantagesBuyerRule5: '',
  advantagesBuyerRule6: '',
  disadvantagesBuyerRule1: '',
  disadvantagesBuyerRule2: '',
  disadvantagesBuyerRule3: '',
  disadvantagesBuyerRule4: '',
  disadvantagesBuyerRule5: '',
  disadvantagesBuyerRule6: '',

  advantagesSellerRule1: '',
  advantagesSellerRule2: '',
  advantagesSellerRule3: '',
  advantagesSellerRule4: '',
  advantagesSellerRule5: '',
  advantagesSellerRule6: '',
  disadvantagesSellerRule1: '',
  disadvantagesSellerRule2: '',
  disadvantagesSellerRule3: '',
  disadvantagesSellerRule4: '',
  disadvantagesSellerRule5: '',
  disadvantagesSellerRule6: '',

  advantagesMivanetRule1: '',
  advantagesMivanetRule2: '',
  advantagesMivanetRule3: '',
  advantagesMivanetRule4: '',
  advantagesMivanetRule5: '',
  advantagesMivanetRule6: '',
  disadvantagesMivanetRule1: '',
  disadvantagesMivanetRule2: '',
  disadvantagesMivanetRule3: '',
  disadvantagesMivanetRule4: '',
  disadvantagesMivanetRule5: '',
  disadvantagesMivanetRule6: '',

  successDialogSurveyScene: 'Your comment has been successfully submitted',
  // Survey Scene--E

  // COMMON --S
  duration: 'for',
  from: 'from $arg0',
  upTo: 'up to $arg0',
  kg: ' Kg',
  kge: 'cost of each Kg',
  moneyUnit: 'T',
  fullMoneyUnit: 'Toman',
  confirm: 'Confirm',
  province: 'province',
  city: 'city'
  // COMMON --E
}
